INSERT INTO customer(CUS_ID,CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER)
VALUES (1,"AAKASH",'9999999999	',"DELHI",'M');
INSERT INTO customer(CUS_ID,CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER)
VALUES	(2,"AMAN",'9785463215',"NOIDA",'M');
INSERT INTO customer(CUS_ID,CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER)
VALUES	(3,"NEHA",'9999999999',"MUMBAI",'F');
INSERT INTO customer(CUS_ID,CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER)
VALUES	(4,"MEGHA",'9994562399	',"KOLKATA",'F');
INSERT INTO customer(CUS_ID,CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER)
VALUES	(5,"PULKIT",'7895999999',"LUCKNOW",'M');