INSERT INTO  category (CAT_ID, CAT_NAME)VALUES (1,'BOOKS');
INSERT INTO  category (CAT_ID, CAT_NAME) VALUES (2,'GAMES');
INSERT INTO  category (CAT_ID, CAT_NAME) VALUES (3,'GROCERIES');
INSERT INTO  category (CAT_ID, CAT_NAME)VALUES (4,'ELECTRONICS');
INSERT INTO  category (CAT_ID, CAT_NAME)VALUES (5,'CLOTHES');